### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by sokoow** [rpgeeganage/ots-share-app#2]
Hey, nice one with this app, I think the idea is very awesome, also you've put a lot of work into it and the prototype works - kudos. Now, I'd love to see a postgres version of it. Also, is adding fileshare possible easily? Can I help somehow?

**Comment by rpgeeganage** [comment]
> Hey, nice one with this app, I think the idea is very awesome, also you've put a lot of work into it and the prototype works - kudos. Now, I'd love to see a postgres version of it. Also, is adding fileshare possible easily? Can I help somehow?
 
Thanks a lot 
I can work on adding Postgress. Probably this weekend. You can contribute for sure. I haven't added a guid to how to contribute. But I'm working on that.

**Comment by rpgeeganage** [comment]
@sokoow ,
I have added support for `Postgres` and `MySQL`. Instructions are updated in the `README`.

**Comment by rpgeeganage** [comment]
@sokoow ,
Added support for small files. (Max 1MB).

**Comment by sokoow** [comment]
nice one, sorry for not replying but I got busy - this is sterling work and a very cool feature set already

**Comment by rpgeeganage** [comment]
@sokoow, thanks a lot. It means a lot. I'll probably keep on adding new features. Please suggest any feature which you think is helpful. I'll close this for now. 🙇
