### ISSUE TITLE
Error building in portainer

### ISSUE THREAD

**Issue by Solaris17** [rpgeeganage/ots-share-app#4]
System: VM
OS: Ubuntu 22.04
RAM: 8gb
Drive: 60GB

Manager: Portainer Community Edition 2.17.0

Issue:

Attempting to build a stack in new portainer. No other containers or software running on system. When building the following error was received.

`failed to deploy a stack: ots-share-mongo-local Pulling 456d651ccb27 Pulling fs layer 0d873b46166f Pulling fs layer b700537f311e Pulling fs layer 8ba0f53e4854 Pulling fs layer 80b58c92c83f Pulling fs layer f4ed2f74d01b Pulling fs layer 0a2bd86063a1 Pulling fs layer 9d3479b42a1a Pulling fs layer 59e7441cc47f Pulling fs layer f4ed2f74d01b Waiting 0a2bd86063a1 Waiting 9d3479b42a1a Waiting 59e7441cc47f Waiting 8ba0f53e4854 Waiting 80b58c92c83f Waiting 0d873b46166f Downloading [===================> ] 757B/1.957kB 0d873b46166f Downloading [==================================================>] 1.957kB/1.957kB 0d873b46166f Verifying Checksum 0d873b46166f Download complete b700537f311e Downloading [> ] 77.54kB/7.59MB 456d651ccb27 Downloading [> ] 277.8kB/26.71MB 456d651ccb27 Downloading [========> ] 4.725MB/26.71MB b700537f311e Downloading [==============> ] 2.211MB/7.59MB 8ba0f53e4854 Downloading [> ] 13.69kB/1.258MB 456d651ccb27 Downloading [======================> ] 11.93MB/26.71MB 8ba0f53e4854 Downloading [====================> ] 524.3kB/1.258MB 8ba0f53e4854 Downloading [==================================================>] 1.258MB/1.258MB 8ba0f53e4854 Verifying Checksum 8ba0f53e4854 Download complete b700537f311e Verifying Checksum b700537f311e Download complete 456d651ccb27 Downloading [========================================> ] 21.4MB/26.71MB 456d651ccb27 Verifying Checksum 456d651ccb27 Download complete 456d651ccb27 Extracting [> ] 294.9kB/26.71MB 80b58c92c83f Downloading [==================================================>] 149B/149B 80b58c92c83f Verifying Checksum 80b58c92c83f Download complete f4ed2f74d01b Downloading [==========================> ] 757B/1.449kB f4ed2f74d01b Downloading [==================================================>] 1.449kB/1.449kB f4ed2f74d01b Verifying Checksum f4ed2f74d01b Download complete 456d651ccb27 Extracting [================> ] 8.552MB/26.71MB 0a2bd86063a1 Downloading [==================================================>] 258B/258B 0a2bd86063a1 Verifying Checksum 0a2bd86063a1 Download complete 456d651ccb27 Extracting [===============================> ] 16.81MB/26.71MB 59e7441cc47f Downloading [=============> ] 1.369kB/4.962kB 59e7441cc47f Downloading [==================================================>] 4.962kB/4.962kB 59e7441cc47f Verifying Checksum 59e7441cc47f Download complete 9d3479b42a1a Downloading [> ] 540kB/129.9MB 456d651ccb27 Extracting [=============================================> ] 24.48MB/26.71MB 9d3479b42a1a Downloading [==> ] 6.433MB/129.9MB 456d651ccb27 Extracting [==================================================>] 26.71MB/26.71MB 456d651ccb27 Pull complete 0d873b46166f Extracting [==================================================>] 1.957kB/1.957kB 0d873b46166f Extracting [==================================================>] 1.957kB/1.957kB 9d3479b42a1a Downloading [======> ] 16.06MB/129.9MB 9d3479b42a1a Downloading [=========> ] 24.6MB/129.9MB 9d3479b42a1a Downloading [=============> ] 34.24MB/129.9MB 0d873b46166f Pull complete b700537f311e Extracting [> ] 98.3kB/7.59MB 9d3479b42a1a Downloading [=================> ] 44.96MB/129.9MB b700537f311e Extracting [===================> ] 2.949MB/7.59MB 9d3479b42a1a Downloading [=====================> ] 54.61MB/129.9MB b700537f311e Extracting [==================================================>] 7.59MB/7.59MB 9d3479b42a1a Downloading [=========================> ] 66.41MB/129.9MB b700537f311e Pull complete 8ba0f53e4854 Extracting [=> ] 32.77kB/1.258MB 9d3479b42a1a Downloading [=============================> ] 76.06MB/129.9MB 8ba0f53e4854 Extracting [==================================================>] 1.258MB/1.258MB 8ba0f53e4854 Pull complete 80b58c92c83f Extracting [==================================================>] 149B/149B 80b58c92c83f Extracting [==================================================>] 149B/149B 9d3479b42a1a Downloading [=================================> ] 87.86MB/129.9MB 80b58c92c83f Pull complete f4ed2f74d01b Extracting [==================================================>] 1.449kB/1.449kB f4ed2f74d01b Extracting [==================================================>] 1.449kB/1.449kB 9d3479b42a1a Downloading [======================================> ] 99.65MB/129.9MB f4ed2f74d01b Pull complete 0a2bd86063a1 Extracting [==================================================>] 258B/258B 0a2bd86063a1 Extracting [==================================================>] 258B/258B 9d3479b42a1a Downloading [==========================================> ] 111.4MB/129.9MB 0a2bd86063a1 Pull complete 9d3479b42a1a Downloading [===============================================> ] 123.2MB/129.9MB 9d3479b42a1a Verifying Checksum 9d3479b42a1a Download complete 9d3479b42a1a Extracting [> ] 557.1kB/129.9MB 9d3479b42a1a Extracting [====> ] 10.58MB/129.9MB 9d3479b42a1a Extracting [========> ] 21.17MB/129.9MB 9d3479b42a1a Extracting [==========> ] 27.85MB/129.9MB 9d3479b42a1a Extracting [==============> ] 37.88MB/129.9MB 9d3479b42a1a Extracting [==================> ] 48.46MB/129.9MB 9d3479b42a1a Extracting [=====================> ] 55.71MB/129.9MB 9d3479b42a1a Extracting [==========================> ] 68.52MB/129.9MB 9d3479b42a1a Extracting [===============================> ] 80.77MB/129.9MB 9d3479b42a1a Extracting [===================================> ] 91.36MB/129.9MB 9d3479b42a1a Extracting [=======================================> ] 102.5MB/129.9MB 9d3479b42a1a Extracting [===========================================> ] 112MB/129.9MB 9d3479b42a1a Extracting [===============================================> ] 123.1MB/129.9MB 9d3479b42a1a Extracting [=================================================> ] 129.8MB/129.9MB 9d3479b42a1a Extracting [==================================================>] 129.9MB/129.9MB 9d3479b42a1a Pull complete 59e7441cc47f Extracting [==================================================>] 4.962kB/4.962kB 59e7441cc47f Extracting [==================================================>] 4.962kB/4.962kB 59e7441cc47f Pull complete ots-share-mongo-local Pulled Network test_default Creating Network test_default Created Container ots-share-mongo-local Creating Container ots-share-build Creating Container ots-share-run-db Creating Container ots-share-mongo-local Created Container ots-share-run Creating Container ots-share-build Created Container ots-share-run-db Created Container ots-share-run Created Container ots-share-run-db Starting Container ots-share-build Starting Container ots-share-mongo-local Starting Container ots-share-build Started Container ots-share-mongo-local Started Container ots-share-run Starting Container ots-share-run-db Started Error response from daemon: driver failed programming external connectivity on endpoint ots-share-run (71610a74ad90eba363966d87e093681a2dbf3eb6dfb02b2eda3786fac66640d8): Bind for 0.0.0.0:9898 failed: port is already allocated`

Attempted Remediation:
Commenting out line 23

New error:

`failed to deploy a stack: ots-share-mongo-local Pulling 456d651ccb27 Pulling fs layer 0d873b46166f Pulling fs layer b700537f311e Pulling fs layer 8ba0f53e4854 Pulling fs layer 80b58c92c83f Pulling fs layer f4ed2f74d01b Pulling fs layer 0a2bd86063a1 Pulling fs layer 9d3479b42a1a Pulling fs layer 59e7441cc47f Pulling fs layer f4ed2f74d01b Waiting 0a2bd86063a1 Waiting 9d3479b42a1a Waiting 59e7441cc47f Waiting 8ba0f53e4854 Waiting 80b58c92c83f Waiting 0d873b46166f Downloading [===================> ] 757B/1.957kB 0d873b46166f Downloading [==================================================>] 1.957kB/1.957kB 0d873b46166f Verifying Checksum 0d873b46166f Download complete b700537f311e Downloading [> ] 77.54kB/7.59MB 456d651ccb27 Downloading [> ] 277.8kB/26.71MB b700537f311e Downloading [=============> ] 1.974MB/7.59MB 456d651ccb27 Downloading [=============> ] 6.974MB/26.71MB b700537f311e Verifying Checksum b700537f311e Download complete 456d651ccb27 Downloading [=======================> ] 12.8MB/26.71MB 456d651ccb27 Downloading [===========================================> ] 23.08MB/26.71MB 456d651ccb27 Verifying Checksum 456d651ccb27 Download complete 80b58c92c83f Downloading [==================================================>] 149B/149B 80b58c92c83f Download complete 456d651ccb27 Extracting [> ] 294.9kB/26.71MB 456d651ccb27 Extracting [================> ] 8.552MB/26.71MB f4ed2f74d01b Downloading [==========================> ] 758B/1.449kB f4ed2f74d01b Downloading [==================================================>] 1.449kB/1.449kB f4ed2f74d01b Verifying Checksum f4ed2f74d01b Download complete 0a2bd86063a1 Downloading [==================================================>] 258B/258B 0a2bd86063a1 Verifying Checksum 0a2bd86063a1 Download complete 456d651ccb27 Extracting [==============================> ] 16.52MB/26.71MB 456d651ccb27 Extracting [=============================================> ] 24.18MB/26.71MB 59e7441cc47f Downloading [=======> ] 757B/4.962kB 59e7441cc47f Downloading [==================================================>] 4.962kB/4.962kB 59e7441cc47f Verifying Checksum 59e7441cc47f Download complete 9d3479b42a1a Downloading [> ] 540.7kB/129.9MB 456d651ccb27 Extracting [=================================================> ] 26.54MB/26.71MB 456d651ccb27 Extracting [==================================================>] 26.71MB/26.71MB 456d651ccb27 Pull complete 0d873b46166f Extracting [==================================================>] 1.957kB/1.957kB 0d873b46166f Extracting [==================================================>] 1.957kB/1.957kB 9d3479b42a1a Downloading [===> ] 8.567MB/129.9MB 9d3479b42a1a Downloading [=====> ] 15.02MB/129.9MB 9d3479b42a1a Downloading [=========> ] 23.59MB/129.9MB 0d873b46166f Pull complete b700537f311e Extracting [> ] 98.3kB/7.59MB 9d3479b42a1a Downloading [============> ] 32.72MB/129.9MB b700537f311e Extracting [===================> ] 2.949MB/7.59MB 9d3479b42a1a Downloading [===============> ] 40.23MB/129.9MB b700537f311e Extracting [==================================================>] 7.59MB/7.59MB 9d3479b42a1a Downloading [===================> ] 50.44MB/129.9MB 8ba0f53e4854 Downloading [> ] 13.69kB/1.258MB b700537f311e Pull complete 9d3479b42a1a Downloading [======================> ] 59.02MB/129.9MB 8ba0f53e4854 Downloading [=========================================> ] 1.039MB/1.258MB 8ba0f53e4854 Downloading [==================================================>] 1.258MB/1.258MB 8ba0f53e4854 Verifying Checksum 8ba0f53e4854 Download complete 8ba0f53e4854 Extracting [=> ] 32.77kB/1.258MB 8ba0f53e4854 Extracting [==================================================>] 1.258MB/1.258MB 8ba0f53e4854 Extracting [==================================================>] 1.258MB/1.258MB 9d3479b42a1a Downloading [===========================> ] 70.89MB/129.9MB 8ba0f53e4854 Pull complete 80b58c92c83f Extracting [==================================================>] 149B/149B 80b58c92c83f Extracting [==================================================>] 149B/149B 9d3479b42a1a Downloading [===============================> ] 80.56MB/129.9MB 80b58c92c83f Pull complete f4ed2f74d01b Extracting [==================================================>] 1.449kB/1.449kB f4ed2f74d01b Extracting [==================================================>] 1.449kB/1.449kB 9d3479b42a1a Downloading [===================================> ] 91.83MB/129.9MB f4ed2f74d01b Pull complete 0a2bd86063a1 Extracting [==================================================>] 258B/258B 0a2bd86063a1 Extracting [==================================================>] 258B/258B 0a2bd86063a1 Pull complete 9d3479b42a1a Downloading [========================================> ] 104.2MB/129.9MB 9d3479b42a1a Downloading [============================================> ] 116MB/129.9MB 9d3479b42a1a Downloading [================================================> ] 125.1MB/129.9MB 9d3479b42a1a Verifying Checksum 9d3479b42a1a Download complete 9d3479b42a1a Extracting [> ] 557.1kB/129.9MB 9d3479b42a1a Extracting [====> ] 10.58MB/129.9MB 9d3479b42a1a Extracting [========> ] 21.17MB/129.9MB 9d3479b42a1a Extracting [==========> ] 28.41MB/129.9MB 9d3479b42a1a Extracting [==============> ] 38.44MB/129.9MB 9d3479b42a1a Extracting [==================> ] 49.02MB/129.9MB 9d3479b42a1a Extracting [=====================> ] 55.71MB/129.9MB 9d3479b42a1a Extracting [==========================> ] 67.96MB/129.9MB 9d3479b42a1a Extracting [==============================> ] 80.22MB/129.9MB 9d3479b42a1a Extracting [==================================> ] 90.8MB/129.9MB 9d3479b42a1a Extracting [=======================================> ] 101.9MB/129.9MB 9d3479b42a1a Extracting [==========================================> ] 111.4MB/129.9MB 9d3479b42a1a Extracting [===============================================> ] 122.6MB/129.9MB 9d3479b42a1a Extracting [=================================================> ] 129.8MB/129.9MB 9d3479b42a1a Extracting [==================================================>] 129.9MB/129.9MB 9d3479b42a1a Pull complete 59e7441cc47f Extracting [==================================================>] 4.962kB/4.962kB 59e7441cc47f Extracting [==================================================>] 4.962kB/4.962kB 59e7441cc47f Pull complete ots-share-mongo-local Pulled failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount4097888629/Dockerfile: no such file or directory`

Context:

This is a new OS and portainer install. The initial concern was that the port in question was not bound. Checked with

`sudo lsof -i -P -n | grep 9898`

Nothing was listed.

**Comment by rpgeeganage** [comment]
@Solaris17 ,
Thanks a lot for the support.
I have added a fix to support with `Portainer`.
I have updated the [README.md](https://github.com/rpgeeganage/ots-share-app#using-with-deploy-tools).
Please refer to it and check.

**Comment by Solaris17** [comment]
This is working great now! Thanks!
