### ISSUE TITLE
support for base url

### ISSUE THREAD

**Issue by sokoow** [rpgeeganage/ots-share-app#7]
Hi @rpgeeganage 

I just tried to put ots behind a load balancer, and I'm getting lots of ERR_SSL_PROTOCOL_ERROR which normally means two things:

- there's SSL/TLS connections being served in the app
- appplication is doing lots of 307 requests cause it can't set proper base url (I can't see it anywhere in the code)

Would you have a moment to look at it pls ?

**Comment by rpgeeganage** [comment]
@sokoow,
I will look into it first thing tomorrow.
(I dont have any redirections at the moment. And I dont serve the app in HTTPS. It’s all http. I only map docker port 80 to host port 8220).
I’ll try to check with nginx and self sign cert

**Comment by rpgeeganage** [comment]
Can u give me a example of a route which you are trying to use. (I tested with ngork while I develop.)

**Comment by sokoow** [comment]
ok, discard that, it was a problem with ssl cert generator from my side - base url would help here, but I'm ok for a moment
